import { getEnvelopeValue } from './getEnvelopeValue';
import { getValueAtTime } from './linear-change';

import {
  restStage,
  attackStage,
  holdStage,
  decayStage,
  sustainStage,
  releaseStage
} from './getEnvelopeValue';

const allStagesHaveTimeState = {
  attackTime: 0.2,
  attackValue: 1,
  holdTime: 0.3,
  decayTime: 0.7,
  sustainValue: 0.5,
  releaseTime: 1.2
};
const skipAttackState = {
  attackTime: 0,
  attackValue: 1,
  holdTime: 0.3,
  decayTime: 0.7,
  sustainValue: 0.5,
  releaseTime: 1.2
};
const skipHoldState = {
  attackTime: 0.2,
  attackValue: 1,
  holdTime: 0,
  decayTime: 0.7,
  sustainValue: 0.5,
  releaseTime: 1.2
};
const skipAttackAndHoldState = {
  attackTime: 0,
  attackValue: 1,
  holdTime: 0,
  decayTime: 0.7,
  sustainValue: 0.5,
  releaseTime: 1.2
};
const skipDecayState = {
  attackTime: 0.2,
  attackValue: 1,
  holdTime: 0.3,
  decayTime: 0,
  sustainValue: 0.5,
  releaseTime: 1.2
};
const skipHoldAndDecayState = {
  attackTime: 0.2,
  attackValue: 1,
  holdTime: 0,
  decayTime: 0,
  sustainValue: 0.5,
  releaseTime: 1.2
};
const skipAttackHoldAndDecayState = {
  attackTime: 0,
  attackValue: 1,
  holdTime: 0,
  decayTime: 0,
  sustainValue: 0.5,
  releaseTime: 1.2
};
const skipReleaseState = {
  attackTime: 0.2,
  attackValue: 1,
  holdTime: 0.3,
  decayTime: 0.7,
  sustainValue: 0.5,
  releaseTime: 0
};

describe('linear envelope generator', () => {
  test.each([
    [10, allStagesHaveTimeState, 0, restStage, 0, undefined, restStage, 0.1, 0, undefined, 0],
    [10, skipAttackHoldAndDecayState, 0, restStage, 0, undefined, restStage, 0.1, 0, undefined, 0],
    [10, skipAttackHoldAndDecayState, 1, restStage, 0, undefined, restStage, 1.1, 0, undefined, 0],
    [10, allStagesHaveTimeState, 0, restStage, 1, undefined, attackStage, 0.1, 0.5, 0, 0.5],
    [10, allStagesHaveTimeState, 2, restStage, 1, undefined, attackStage, 0.1, 0.5, 0, 0.5],
    [5, allStagesHaveTimeState, 2, restStage, 1, undefined, holdStage, 0, 0, undefined, 1],
    [2, allStagesHaveTimeState, 2, restStage, 1, undefined, decayStage, 0, 0, undefined, 1],
    [0.5, allStagesHaveTimeState, 2, restStage, 1, undefined, sustainStage, 0.8, 0, undefined, 0.5],
    [10, skipAttackState, 0, restStage, 1, undefined, holdStage, 0.1, 1 / 3, undefined, 1],
    [
      10,
      skipAttackAndHoldState,
      0,
      restStage,
      1,
      undefined,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      restStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [
      10,
      allStagesHaveTimeState,
      0,
      attackStage,
      1,
      undefined,
      attackStage,
      0.1,
      0.5,
      undefined,
      0.5
    ],
    [10, allStagesHaveTimeState, 0, attackStage, 1, 0, attackStage, 0.1, 0.5, 0, 0.5],
    [10, allStagesHaveTimeState, 0, attackStage, 1, 0.2, attackStage, 0.1, 0.5, 0.2, 0.6],
    [10, allStagesHaveTimeState, 0.1, attackStage, 1, undefined, holdStage, 0, 0, undefined, 1],
    [
      10,
      allStagesHaveTimeState,
      0.3,
      attackStage,
      1,
      undefined,
      holdStage,
      0.2,
      2 / 3,
      undefined,
      1
    ],
    [
      10,
      allStagesHaveTimeState,
      0.5,
      attackStage,
      1,
      undefined,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [
      10,
      allStagesHaveTimeState,
      1,
      attackStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [
      10,
      allStagesHaveTimeState,
      1.1,
      attackStage,
      1,
      undefined,
      sustainStage,
      0,
      0,
      undefined,
      0.5
    ],
    [5, allStagesHaveTimeState, 0, attackStage, 1, undefined, holdStage, 0, 0, undefined, 1],
    [
      5,
      allStagesHaveTimeState,
      0.5,
      attackStage,
      1,
      undefined,
      decayStage,
      0.2,
      2 / 7,
      undefined,
      1 - 2 / 14
    ],
    [2, allStagesHaveTimeState, 0, attackStage, 1, undefined, decayStage, 0, 0, undefined, 1],
    [5, allStagesHaveTimeState, 1, attackStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      0.5,
      allStagesHaveTimeState,
      0,
      attackStage,
      1,
      undefined,
      sustainStage,
      0.8,
      0,
      undefined,
      0.5
    ],
    [
      10,
      allStagesHaveTimeState,
      0.2,
      attackStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      1,
      1 - 1 / 12
    ],
    [
      10,
      allStagesHaveTimeState,
      0.2,
      attackStage,
      0,
      0.11,
      releaseStage,
      0.1,
      1 / 12,
      1,
      1 - 1 / 12
    ],
    [
      10,
      allStagesHaveTimeState,
      0.1,
      attackStage,
      0,
      0.11,
      releaseStage,
      0.1,
      1 / 12,
      0.11 + (1 - 0.11) / 2,
      0.11 + (1 - 0.11) / 2 - (0.11 + (1 - 0.11) / 2) / 12
    ],
    [10, skipAttackState, 0.2, attackStage, 0, undefined, releaseStage, 0.1, 1 / 12, 1, 1 - 1 / 12],
    [
      10,
      skipAttackAndHoldState,
      0.2,
      attackStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      1 - 2 / 14,
      1 - 2 / 14 - (1 - 2 / 14) / 12
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0.2,
      attackStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 1 / 24
    ],
    [10, skipDecayState, 0.2, attackStage, 0, undefined, releaseStage, 0.1, 1 / 12, 1, 1 - 1 / 12],
    [
      10,
      skipDecayState,
      0.1,
      attackStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 0.5 / 12
    ],
    [10, skipDecayState, 0.1, attackStage, 0, 0, releaseStage, 0.1, 1 / 12, 0.5, 0.5 - 0.5 / 12],
    [
      10,
      skipDecayState,
      0.1,
      attackStage,
      0,
      0.4,
      releaseStage,
      0.1,
      1 / 12,
      0.4 + (1 - 0.4) / 2,
      0.4 + (1 - 0.4) / 2 - (0.4 + (1 - 0.4) / 2) / 12
    ],
    [
      10,
      skipHoldAndDecayState,
      0.2,
      attackStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [10, skipHoldAndDecayState, 0.1, attackStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      10,
      skipHoldAndDecayState,
      0.2,
      attackStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 1 / 24
    ],
    [10, skipHoldState, 0.2, attackStage, 0, undefined, releaseStage, 0.1, 1 / 12, 1, 1 - 1 / 12],
    [10, skipReleaseState, 0.1, attackStage, 0, undefined, restStage, 0.1, 0, undefined, 0],
    [10, skipAttackState, 0.1, attackStage, 1, undefined, holdStage, 0.2, 2 / 3, undefined, 1],
    [10, skipAttackState, 0.2, attackStage, 1, undefined, decayStage, 0, 0, undefined, 1],
    [
      10,
      skipAttackState,
      0.3,
      attackStage,
      1,
      undefined,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [10, skipAttackState, 0.9, attackStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [10, skipAttackState, 1, attackStage, 1, undefined, sustainStage, 0.1, 0, undefined, 0.5],
    [
      10,
      skipAttackAndHoldState,
      0.1,
      attackStage,
      1,
      undefined,
      decayStage,
      0.2,
      2 / 7,
      undefined,
      1 - 2 / 14
    ],
    [
      10,
      skipAttackAndHoldState,
      0.6,
      attackStage,
      1,
      undefined,
      sustainStage,
      0,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackAndHoldState,
      0.7,
      attackStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      1.1,
      attackStage,
      1,
      undefined,
      sustainStage,
      1.2,
      0,
      undefined,
      0.5
    ],
    [10, allStagesHaveTimeState, 0.1, holdStage, 1, undefined, holdStage, 0.2, 2 / 3, undefined, 1],
    [10, allStagesHaveTimeState, 0.2, holdStage, 1, undefined, decayStage, 0, 0, undefined, 1],
    [
      10,
      allStagesHaveTimeState,
      0.3,
      holdStage,
      1,
      undefined,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [
      10,
      allStagesHaveTimeState,
      0.8,
      holdStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [10, allStagesHaveTimeState, 0.9, holdStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      10,
      skipAttackAndHoldState,
      0,
      holdStage,
      1,
      undefined,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [10, skipAttackAndHoldState, 0.6, holdStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      10,
      skipAttackAndHoldState,
      0.7,
      holdStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      holdStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [10, skipAttackState, 0.1, holdStage, 1, undefined, holdStage, 0.2, 2 / 3, undefined, 1],
    [10, skipAttackState, 0.2, holdStage, 1, undefined, decayStage, 0, 0, undefined, 1],
    [10, skipDecayState, 0.2, holdStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [10, skipHoldAndDecayState, 0, holdStage, 1, undefined, sustainStage, 0.1, 0, undefined, 0.5],
    [10, skipHoldState, 0, holdStage, 1, undefined, decayStage, 0.1, 1 / 7, undefined, 1 - 1 / 14],
    [10, skipHoldState, 0.7, holdStage, 1, undefined, sustainStage, 0.1, 0, undefined, 0.5],
    [
      2,
      allStagesHaveTimeState,
      0,
      holdStage,
      1,
      undefined,
      decayStage,
      0.2,
      2 / 7,
      undefined,
      1 - 2 / 14
    ],
    [
      2,
      allStagesHaveTimeState,
      0.1,
      holdStage,
      1,
      undefined,
      decayStage,
      0.3,
      3 / 7,
      undefined,
      1 - 3 / 14
    ],
    [
      2,
      allStagesHaveTimeState,
      0.4,
      holdStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [2, allStagesHaveTimeState, 0.5, holdStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [1, allStagesHaveTimeState, 0, holdStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      10,
      allStagesHaveTimeState,
      0,
      holdStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      1,
      1 - 1 / 12
    ],
    [
      10,
      allStagesHaveTimeState,
      10,
      holdStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 1 / 24
    ],
    [
      10,
      skipAttackAndHoldState,
      0,
      holdStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      1,
      1 - 1 / 12
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      holdStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 1 / 24
    ],
    [10, skipAttackState, 0, holdStage, 0, undefined, releaseStage, 0.1, 1 / 12, 1, 1 - 1 / 12],
    [10, skipDecayState, 0, holdStage, 0, undefined, releaseStage, 0.1, 1 / 12, 1, 1 - 1 / 12],
    [
      10,
      skipHoldAndDecayState,
      0,
      holdStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 1 / 24
    ],
    [10, skipHoldState, 0, holdStage, 0, undefined, releaseStage, 0.1, 1 / 12, 1, 1 - 1 / 12],
    [10, skipReleaseState, 0, holdStage, 0, undefined, restStage, 0.1, 0, undefined, 0],
    [
      10,
      allStagesHaveTimeState,
      0,
      decayStage,
      1,
      undefined,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [
      10,
      allStagesHaveTimeState,
      0.5,
      decayStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [10, allStagesHaveTimeState, 0.6, decayStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      10,
      skipAttackAndHoldState,
      0.5,
      decayStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [10, skipAttackAndHoldState, 0.6, decayStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      decayStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0.6,
      decayStage,
      1,
      undefined,
      sustainStage,
      0.7,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0.7,
      decayStage,
      1,
      undefined,
      sustainStage,
      0.8,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackState,
      0.5,
      decayStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [10, skipAttackState, 0.6, decayStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [10, skipDecayState, 0.5, decayStage, 1, undefined, sustainStage, 0.6, 0, undefined, 0.5],
    [10, skipDecayState, 0.6, decayStage, 1, undefined, sustainStage, 0.7, 0, undefined, 0.5],
    [
      10,
      skipHoldAndDecayState,
      0.5,
      decayStage,
      1,
      undefined,
      sustainStage,
      0.6,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipHoldAndDecayState,
      0.6,
      decayStage,
      1,
      undefined,
      sustainStage,
      0.7,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipHoldState,
      0.5,
      decayStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [10, skipHoldState, 0.6, decayStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      10,
      skipReleaseState,
      0.5,
      decayStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [10, skipReleaseState, 0.6, decayStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [
      5,
      allStagesHaveTimeState,
      0,
      decayStage,
      1,
      undefined,
      decayStage,
      0.2,
      2 / 7,
      undefined,
      1 - 2 / 14
    ],
    [
      5,
      allStagesHaveTimeState,
      0.4,
      decayStage,
      1,
      undefined,
      decayStage,
      0.6,
      6 / 7,
      undefined,
      1 - 6 / 14
    ],
    [5, allStagesHaveTimeState, 0.5, decayStage, 1, undefined, sustainStage, 0, 0, undefined, 0.5],
    [1, allStagesHaveTimeState, 0, decayStage, 1, undefined, sustainStage, 0.3, 0, undefined, 0.5],
    [
      10,
      allStagesHaveTimeState,
      0,
      decayStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      1,
      1 - 1 / 12
    ],
    [
      10,
      skipAttackAndHoldState,
      0,
      decayStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      1,
      1 - 1 / 12
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      decayStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 1 / 24
    ],
    [10, skipAttackState, 0, decayStage, 0, undefined, releaseStage, 0.1, 1 / 12, 1, 1 - 1 / 12],
    [10, skipDecayState, 2, decayStage, 0, undefined, releaseStage, 0.1, 1 / 12, 0.5, 0.5 - 1 / 24],
    [10, skipReleaseState, 0, decayStage, 0, undefined, restStage, 0.1, 0, undefined, 0],
    [
      10,
      allStagesHaveTimeState,
      0,
      sustainStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackAndHoldState,
      0,
      sustainStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      sustainStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [10, skipAttackState, 0, sustainStage, 1, undefined, sustainStage, 0.1, 0, undefined, 0.5],
    [10, skipDecayState, 0, sustainStage, 1, undefined, sustainStage, 0.1, 0, undefined, 0.5],
    [
      10,
      skipHoldAndDecayState,
      0,
      sustainStage,
      1,
      undefined,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [10, skipHoldState, 0, sustainStage, 1, undefined, sustainStage, 0.1, 0, undefined, 0.5],
    [10, skipReleaseState, 0, sustainStage, 1, undefined, sustainStage, 0.1, 0, undefined, 0.5],
    [
      10,
      allStagesHaveTimeState,
      20,
      sustainStage,
      1,
      undefined,
      sustainStage,
      20.1,
      0,
      undefined,
      0.5
    ],
    [
      10,
      allStagesHaveTimeState,
      20,
      sustainStage,
      0,
      undefined,
      releaseStage,
      0.1,
      1 / 12,
      0.5,
      0.5 - 1 / 24
    ],
    [10, skipReleaseState, 0, sustainStage, 0, undefined, restStage, 0.1, 0, undefined, 0],
    [
      10,
      allStagesHaveTimeState,
      0,
      releaseStage,
      0,
      0.75,
      releaseStage,
      0.1,
      1 / 12,
      0.75,
      0.75 - 0.75 / 12
    ],
    [10, allStagesHaveTimeState, 1, releaseStage, 0, 0.5, releaseStage, 1.1, 11 / 12, 0.5, 1 / 24],
    [10, allStagesHaveTimeState, 1.1, releaseStage, 0, 0.5, restStage, 0, 0, undefined, 0],
    [5, allStagesHaveTimeState, 0, releaseStage, 0, 1, releaseStage, 0.2, 1 / 6, 1, 1 - 1 / 6],
    [5, allStagesHaveTimeState, 0.9, releaseStage, 0, 0.5, releaseStage, 1.1, 11 / 12, 0.5, 1 / 24],
    [5, allStagesHaveTimeState, 1, releaseStage, 0, 0.5, restStage, 0, 0, undefined, 0],
    [0.5, allStagesHaveTimeState, 0, releaseStage, 0, 1, restStage, 0.8, 0, undefined, 0],
    [10, skipReleaseState, 0, releaseStage, 0, 0.5, restStage, 0.1, 0, undefined, 0],
    [10, allStagesHaveTimeState, 0, releaseStage, 1, 0.6, attackStage, 0.1, 0.5, 0.6, 0.8],
    [5, allStagesHaveTimeState, 0, releaseStage, 1, 0.15, holdStage, 0, 0, undefined, 1],
    [0.5, allStagesHaveTimeState, 0, releaseStage, 1, 1, sustainStage, 0.8, 0, undefined, 0.5],
    [
      10,
      skipAttackAndHoldState,
      0,
      releaseStage,
      1,
      0.75,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      releaseStage,
      1,
      0.5,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [10, skipAttackState, 0, releaseStage, 1, 0.5, holdStage, 0.1, 1 / 3, undefined, 1],
    [10, skipDecayState, 0, releaseStage, 1, 1, attackStage, 0.1, 0.5, 1, 1],
    [10, skipReleaseState, 0, releaseStage, 1, 0.7, attackStage, 0.1, 0.5, 0, 0.5],
    [10, allStagesHaveTimeState, 0.3, releaseStage, 1, 0.6, attackStage, 0.1, 0.5, 0.45, 0.725],
    [
      10,
      skipAttackAndHoldState,
      0,
      releaseStage,
      1,
      0.5,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [
      10,
      skipAttackAndHoldState,
      2,
      releaseStage,
      1,
      0.5,
      decayStage,
      0.1,
      1 / 7,
      undefined,
      1 - 1 / 14
    ],
    [
      10,
      skipAttackHoldAndDecayState,
      0,
      releaseStage,
      1,
      0.5,
      sustainStage,
      0.1,
      0,
      undefined,
      0.5
    ],
    [10, skipAttackState, 0, releaseStage, 1, 1, holdStage, 0.1, 1 / 3, undefined, 1],
    [2, skipAttackState, 0, releaseStage, 1, 1, decayStage, 0.2, 2 / 7, undefined, 1 - 2 / 14],
    [10, skipAttackState, 1, releaseStage, 1, 0.1, holdStage, 0.1, 1 / 3, undefined, 1],
    [10, skipDecayState, 0, releaseStage, 1, 0.5, attackStage, 0.1, 0.5, 0.5, 0.75],
    [10, skipReleaseState, 0, releaseStage, 1, 1, attackStage, 0.1, 0.5, 0, 0.5]
  ])(
    'transitions to the correct state. sample rate: %f, start state: %j, seconds since state transition: %f, start stage: %s, trigger value: %f, value on release: %f, expected stage: %s, expected seconds since transition: %f, expected stage progress: %s, expected value on release: %f, expected output value: %f',
    (
      sampleRate,
      state,
      secondsSinceStateTransition,
      stage,
      inputSample,
      valueOnTriggerChange,
      expectedStage,
      expectedSecondsSinceStateTransitions,
      expectedStageProgress,
      expectedValueOnTriggerChange,
      expectedValue
    ) => {
      const result = getEnvelopeValue(
        getValueAtTime,
        sampleRate,
        state,
        secondsSinceStateTransition,
        stage,
        inputSample,
        valueOnTriggerChange
      );
      expect(result.stage).toBe(expectedStage);
      expect(result.secondsSinceStateTransition).toBeCloseTo(
        expectedSecondsSinceStateTransitions,
        6
      );
      expect(result.stageProgress).toBeCloseTo(expectedStageProgress, 6);
      if (expectedValueOnTriggerChange === undefined) {
        expect(result.valueOnTriggerChange).toBeUndefined();
      } else {
        expect(result.valueOnTriggerChange).toBeCloseTo(expectedValueOnTriggerChange, 6);
      }

      expect(result.outputValue).toBeCloseTo(expectedValue, 6);
    }
  );
});
